- name: Create a new database with name 'wp_prd'
  mysql_db:
    name: wp_db_prd
    state: present
  when: ansible_facts['distribution'] == "CentOS"
  

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: wp_user_01
    password: "{{ dbpass }}"
    priv: 'wp_db_prd.*:ALL,GRANT'
    host: "%"
    state: present
  when: ansible_facts['distribution'] == "CentOS"